pi_dash:
    resource: "@PiDashBundle/Resources/config/routing.yml"
    prefix:   /

mail_mail:
    resource: "@MailMailBundle/Resources/config/routing.yml"
    prefix:   /

pi_pi:
    resource: "@PiPiBundle/Resources/config/routing.yml"
    prefix:   /
pi_piadmin:
    resource: "@PiPiAdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin