<?php

namespace Pi\PiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DealcourantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealcourantRepository extends EntityRepository
{
  
}
