<?php

namespace Pi\PiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewslettreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewslettreRepository extends EntityRepository
{
}
