parameters:
#    mail_mail.example.class: Mail\MailBundle\Example

services:
#    mail_mail.example:
#        class: %mail_mail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
